steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-dbt-docker-image'
    args: ['build', '--build-arg', 'PROJECT_ID=${_PROJECT}', '--build-arg', 'BQ_DATASET=datapay', '--build-arg', 'DBT_DIR=.',  '-t', 'europe-west1-docker.pkg.dev/${_PROJECT}/${_REPOSITORY}/${_IMAGE}:latest', '-f', 'Dockerfile', '.']

options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'europe-west1-docker.pkg.dev/${_PROJECT}/${_REPOSITORY}/${_IMAGE}'
timeout: 1800s

# gcloud builds submit --config=cloudbuild.yml --substitutions=_PROJECT="jacobhp-personal",_REPOSITORY="datapay-dbt",_IMAGE="dbt" .