
name: Build Artifact Registry Images

on:
  push:
    branches: [ 'main' ]

env:
  PROJECT_ID: jacobhp-personal
  GAR_LOCATION: todo

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Google Auth
        id: auth 
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>=363.0.0'
      
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Build extract image'
        working-directory: ./extract
        run: 'gcloud builds submit --config=cloudbuild.yml --substitutions=_PROJECT="jacobhp-personal",_REPOSITORY="datapay-extract",_IMAGE="extract" .'

      - name: 'Build dbt image'
        working-directory: ./dbt
        run: 'gcloud builds submit --config=cloudbuild.yml --substitutions=_PROJECT="jacobhp-personal",_REPOSITORY="datapay-dbt",_IMAGE="dbt" .'

      - name: 'Deploy workflows'
        working-directory: ./workflows
        run: 'gcloud workflows deploy reed_workflow --location="europe-west1" --source=reed_workflow.yml --description="Reed ELT orchestration"'